leftnav:
- identifier: 592f975d-cd9c-9be0-8a9f-92805e050ffb
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: e4c6147b-0024-f18e-8557-dcdb1f1185a7
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: e07e15fc-a31d-9b90-9ddc-5683781799d3
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: 00edd310-9daf-889d-1639-19727717d5fd
  name: Assignments
  url: /pages/assignments
  weight: 40
